#!/usr/bin/env php
<?php

declare(strict_types=1);

function checkVersion($min = '8.1'): void
{
    if (version_compare(PHP_VERSION, $min, '<')) {
        exit(sprintf('Your PHP version must be %s or higher. Your current PHP version is %s', $min, PHP_VERSION));
    }
}

function run(): ?bool
{
    checkVersion();

    $host         = 'localhost';
    $port         = 8000;
    $documentRoot = __DIR__ . DIRECTORY_SEPARATOR . 'public';

    return passthru(PHP_BINARY . " -S {$host}:{$port} -t {$documentRoot}");
}

run();
